# Generated by Django 2.2.6 on 2019-10-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
